const styles = {
  card: {
    p: 3,
    textAlign: "center",
    position: "relative",
    mx: "auto",
    backgroundColor: "#f6faff",
    borderRadius: "20px",
    boxShadow: "none",
    width: "75%",
  },
  imageWrapper: {
    position: "relative",
    display: "inline-block",
  },
  image: {
    maxHeight: 550,
  },
  zoomIcon: {
    position: "absolute",
    top: "-8px",
    right: "-60px",
    borderRadius: "50%",
    padding: "4px",
    zIndex: 2,
    cursor: "pointer",
    "& .MuiSvgIcon-root": {
      color: "#a3adab",
    },
  },
  heartScanner: {
    width: 60,
    height: 60,
    borderRadius: "8px",
    position: "absolute",
    zIndex: 1,
    top: "40%",
    right: "60%",
  },
  heartLabel: {
    position: "absolute",
    top: "41%",
    right: "50%",
    backgroundColor: "#3f51b5",
    color: "#fff",
    px: 2,
    py: 1,
    borderRadius: "12px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    boxShadow: 3,
    whiteSpace: "nowrap",
    zIndex: 2,
  },
  legScanner: {
    width: 60,
    height: 60,
    borderRadius: "8px",
    position: "absolute",
    zIndex: 1,
    top: "82%",
    left: "33%",
  },
  legLabel: {
    position: "absolute",
    top: "82%",
    left: "22%",
    backgroundColor: "#00cfff",
    color: "#fff",
    px: 2,
    py: 1,
    borderRadius: "12px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    boxShadow: 3,
    whiteSpace: "nowrap",
    zIndex: 2,
    paddingLeft: "22px",
  },
  scannerBox: {
    width: 60,
    height: 60,
    border: "2px solid rgba(0, 0, 255, 0.6)",
    borderRadius: "8px",
    backgroundColor: "rgba(0, 0, 255, 0.2)",
    position: "absolute",
    zIndex: 1,
  },
};

export default styles;
